Implementing the Game of life by Conway.
We should use a numpy array of zeros and ones to model the world our cells live in. Furthermore there has to be a function which determins the time evolution of the system accordingly to the rules.

In [2]:
import numpy as np

In [4]:
def neigh(s,i,j):
    neighbors = 0
    #a->rows b->columns
    for a in range(i-1,i+2):
        for b in range(j-1,j+2):
            if(a != i or b != j):
                if(s[a][b] == 1):
                    neighbors += 1
    return neighbors

def control(s,N):
    c = np.zeros((N,N), dtype=int)
    for i in range(1,N-1):
        for j in range(1,N-1):
            cell = s[i][j]
            if(cell == 1):
                if(neigh(s,i,j) < 2):
                    c[i][j] = -1
                elif(neigh(s,i,j) > 3):
                    c[i][j] = -1
                else:
                    c[i][j] = 0
            else:
                if(neigh(s,i,j) == 3):
                    c[i][j] = 1
                else:
                    c[i][j] = 0
    return c
#dimension of our squared world
N = 15
#system initialization to hoscillator for an N = 10 world
# s = np.zeros((N,N), dtype=int)
# s[4][3], s[4][4], s[4][5] = 1, 1, 1
#casual system
s = np.random.randint(0,2,(N,N), dtype = int)
#Dead borders
s[:,0] = np.zeros(N, dtype = int)
s[:,N-1] = np.zeros(N, dtype = int)
s[0,:] = np.zeros(N, dtype = int)
s[N-1,:] = np.zeros(N, dtype = int)
#time duration (we consider a discrete time with timestep = 1)
T = 100
print(s)
for i in range(T):
    c = control(s,N)
    s = s + c
    print(s)
    

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 0 1 1 0 1 0]
 [0 1 1 0 0 1 1 0 1 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 1 1 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 1 1 1 1 0 1 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 1 0 0]
 [0 0 1 1 1 0 0 1 1 0 1 1 1 1 0]
 [0 0 1 1 0 1 1 1 0 1 0 0 0 0 0]
 [0 1 1 0 0 1 0 1 1 0 1 0 0 0 0]
 [0 1 0 0 1 1 1 1 1 0 0 1 1 1 0]
 [0 1 0 1 1 0 0 1 1 0 1 0 1 1 0]
 [0 0 1 1 0 0 0 1 1 1 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 1 1 1 1 0 0]
 [0 1 1 1 1 0 0 0 1 0 0 0 0 1 0]
 [0 1 1 0 0 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 1 1 1 1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 1 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 